/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MeRouteImport } from './routes/me'
import { Route as InstallRouteImport } from './routes/install'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SopsIndexRouteImport } from './routes/sops.index'
import { Route as GuideIndexRouteImport } from './routes/guide.index'
import { Route as SopsSopIdRouteImport } from './routes/sops.$sopId'
import { Route as GuideAdminRouteImport } from './routes/guide.admin'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as AdminVaIdRouteImport } from './routes/admin_.$vaId'
import { Route as AdminInviteTokenRouteImport } from './routes/admin-invite.$token'
import { Route as ApiPublicExtensionVersionRouteImport } from './routes/api/public/extension-version'
import { Route as ApiPublicDesktopVersionRouteImport } from './routes/api/public/desktop-version'
import { Route as AdminInvoicesInvoiceIdRouteImport } from './routes/admin_.invoices.$invoiceId'
import { Route as ApiPublicHooksCleanupScreenshotsRouteImport } from './routes/api/public/hooks/cleanup-screenshots'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsIndexRoute = SopsIndexRouteImport.update({
  id: '/sops/',
  path: '/sops/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsSopIdRoute = SopsSopIdRouteImport.update({
  id: '/sops/$sopId',
  path: '/sops/$sopId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideAdminRoute = GuideAdminRouteImport.update({
  id: '/guide/admin',
  path: '/guide/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaIdRoute = AdminVaIdRouteImport.update({
  id: '/admin_/$vaId',
  path: '/admin/$vaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteTokenRoute = AdminInviteTokenRouteImport.update({
  id: '/admin-invite/$token',
  path: '/admin-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionVersionRoute =
  ApiPublicExtensionVersionRouteImport.update({
    id: '/api/public/extension-version',
    path: '/api/public/extension-version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDesktopVersionRoute = ApiPublicDesktopVersionRouteImport.update({
  id: '/api/public/desktop-version',
  path: '/api/public/desktop-version',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesInvoiceIdRoute = AdminInvoicesInvoiceIdRouteImport.update({
  id: '/admin_/invoices/$invoiceId',
  path: '/admin/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupScreenshotsRoute =
  ApiPublicHooksCleanupScreenshotsRouteImport.update({
    id: '/api/public/hooks/cleanup-screenshots',
    path: '/api/public/hooks/cleanup-screenshots',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/financials': typeof FinancialsRoute
  '/install': typeof InstallRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/admin/$vaId': typeof AdminVaIdRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/guide/admin': typeof GuideAdminRoute
  '/sops/$sopId': typeof SopsSopIdRoute
  '/guide/': typeof GuideIndexRoute
  '/sops/': typeof SopsIndexRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/api/public/desktop-version': typeof ApiPublicDesktopVersionRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/api/public/hooks/cleanup-screenshots': typeof ApiPublicHooksCleanupScreenshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/financials': typeof FinancialsRoute
  '/install': typeof InstallRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/admin/$vaId': typeof AdminVaIdRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/guide/admin': typeof GuideAdminRoute
  '/sops/$sopId': typeof SopsSopIdRoute
  '/guide': typeof GuideIndexRoute
  '/sops': typeof SopsIndexRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/api/public/desktop-version': typeof ApiPublicDesktopVersionRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/api/public/hooks/cleanup-screenshots': typeof ApiPublicHooksCleanupScreenshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consent': typeof ConsentRoute
  '/financials': typeof FinancialsRoute
  '/install': typeof InstallRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/admin-invite/$token': typeof AdminInviteTokenRoute
  '/admin_/$vaId': typeof AdminVaIdRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/guide/admin': typeof GuideAdminRoute
  '/sops/$sopId': typeof SopsSopIdRoute
  '/guide/': typeof GuideIndexRoute
  '/sops/': typeof SopsIndexRoute
  '/admin_/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/api/public/desktop-version': typeof ApiPublicDesktopVersionRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/api/public/hooks/cleanup-screenshots': typeof ApiPublicHooksCleanupScreenshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/consent'
    | '/financials'
    | '/install'
    | '/me'
    | '/reset-password'
    | '/settings'
    | '/admin-invite/$token'
    | '/admin/$vaId'
    | '/admin/settings'
    | '/c/$token'
    | '/guide/admin'
    | '/sops/$sopId'
    | '/guide/'
    | '/sops/'
    | '/admin/invoices/$invoiceId'
    | '/api/public/desktop-version'
    | '/api/public/extension-version'
    | '/api/public/hooks/cleanup-screenshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/consent'
    | '/financials'
    | '/install'
    | '/me'
    | '/reset-password'
    | '/settings'
    | '/admin-invite/$token'
    | '/admin/$vaId'
    | '/admin/settings'
    | '/c/$token'
    | '/guide/admin'
    | '/sops/$sopId'
    | '/guide'
    | '/sops'
    | '/admin/invoices/$invoiceId'
    | '/api/public/desktop-version'
    | '/api/public/extension-version'
    | '/api/public/hooks/cleanup-screenshots'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/consent'
    | '/financials'
    | '/install'
    | '/me'
    | '/reset-password'
    | '/settings'
    | '/admin-invite/$token'
    | '/admin_/$vaId'
    | '/admin_/settings'
    | '/c/$token'
    | '/guide/admin'
    | '/sops/$sopId'
    | '/guide/'
    | '/sops/'
    | '/admin_/invoices/$invoiceId'
    | '/api/public/desktop-version'
    | '/api/public/extension-version'
    | '/api/public/hooks/cleanup-screenshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConsentRoute: typeof ConsentRoute
  FinancialsRoute: typeof FinancialsRoute
  InstallRoute: typeof InstallRoute
  MeRoute: typeof MeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  AdminInviteTokenRoute: typeof AdminInviteTokenRoute
  AdminVaIdRoute: typeof AdminVaIdRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CTokenRoute: typeof CTokenRoute
  GuideAdminRoute: typeof GuideAdminRoute
  SopsSopIdRoute: typeof SopsSopIdRoute
  GuideIndexRoute: typeof GuideIndexRoute
  SopsIndexRoute: typeof SopsIndexRoute
  AdminInvoicesInvoiceIdRoute: typeof AdminInvoicesInvoiceIdRoute
  ApiPublicDesktopVersionRoute: typeof ApiPublicDesktopVersionRoute
  ApiPublicExtensionVersionRoute: typeof ApiPublicExtensionVersionRoute
  ApiPublicHooksCleanupScreenshotsRoute: typeof ApiPublicHooksCleanupScreenshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops/': {
      id: '/sops/'
      path: '/sops'
      fullPath: '/sops/'
      preLoaderRoute: typeof SopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/guide'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops/$sopId': {
      id: '/sops/$sopId'
      path: '/sops/$sopId'
      fullPath: '/sops/$sopId'
      preLoaderRoute: typeof SopsSopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/admin': {
      id: '/guide/admin'
      path: '/guide/admin'
      fullPath: '/guide/admin'
      preLoaderRoute: typeof GuideAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$vaId': {
      id: '/admin_/$vaId'
      path: '/admin/$vaId'
      fullPath: '/admin/$vaId'
      preLoaderRoute: typeof AdminVaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-invite/$token': {
      id: '/admin-invite/$token'
      path: '/admin-invite/$token'
      fullPath: '/admin-invite/$token'
      preLoaderRoute: typeof AdminInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension-version': {
      id: '/api/public/extension-version'
      path: '/api/public/extension-version'
      fullPath: '/api/public/extension-version'
      preLoaderRoute: typeof ApiPublicExtensionVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop-version': {
      id: '/api/public/desktop-version'
      path: '/api/public/desktop-version'
      fullPath: '/api/public/desktop-version'
      preLoaderRoute: typeof ApiPublicDesktopVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/invoices/$invoiceId': {
      id: '/admin_/invoices/$invoiceId'
      path: '/admin/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-screenshots': {
      id: '/api/public/hooks/cleanup-screenshots'
      path: '/api/public/hooks/cleanup-screenshots'
      fullPath: '/api/public/hooks/cleanup-screenshots'
      preLoaderRoute: typeof ApiPublicHooksCleanupScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConsentRoute: ConsentRoute,
  FinancialsRoute: FinancialsRoute,
  InstallRoute: InstallRoute,
  MeRoute: MeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  AdminInviteTokenRoute: AdminInviteTokenRoute,
  AdminVaIdRoute: AdminVaIdRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CTokenRoute: CTokenRoute,
  GuideAdminRoute: GuideAdminRoute,
  SopsSopIdRoute: SopsSopIdRoute,
  GuideIndexRoute: GuideIndexRoute,
  SopsIndexRoute: SopsIndexRoute,
  AdminInvoicesInvoiceIdRoute: AdminInvoicesInvoiceIdRoute,
  ApiPublicDesktopVersionRoute: ApiPublicDesktopVersionRoute,
  ApiPublicExtensionVersionRoute: ApiPublicExtensionVersionRoute,
  ApiPublicHooksCleanupScreenshotsRoute: ApiPublicHooksCleanupScreenshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
